name = "The Beast Churns"
author = "Grace"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9a3c87c4c0299a47ca054fd25e86d13ef391b29fba5c114766640f963ff747b"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
